"""
Django settings for DurielMedic project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv('SECRET_KEY', 'fallback-secret-key')
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY not set in environment variables!")


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env_bool('DEBUG', False)
RUNNING_DEV_SERVER = "runserver" in sys.argv



ALLOWED_HOSTS = [
    'durielmedic.pythonanywhere.com',
    'www.durielmedic.pythonanywhere.com',
    'https://durielmedic.com.ng',
    'www.durielmedic.com.ng',
    'durielmedic.com.ng',
    'localhost',
    '127.0.0.1',
    *[host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()],
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DurielMedicApp',
    'core',
    'DurielEyeApp',
    'DurielDentalApp',
    'crispy_forms',
    'crispy_tailwind',
     'crum',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
    'core.middleware.ClinicMiddleware',
  

]

ROOT_URLCONF = 'DurielMedic.urls'
# ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 'core.context_processors.clinic_context',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'DurielMedic.wsgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'duriel_med',
#         'USER': 'postgres',
#         'PASSWORD': 'Legacy@90',
#         'HOST': '10.255.255.254',
#         'PORT': 5432,
#     }
# }

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# Server-to-server clinic sync.
# Central/cloud config stays in env. Local clinic servers are activated from a
# cloud URL and store their sync config in SQLite ServerSyncState.
SYNC_SERVER_ROLE = os.getenv('SYNC_SERVER_ROLE', 'standalone').strip().lower()
SYNC_SHARED_SECRET = os.getenv('SYNC_SHARED_SECRET', '')
SYNC_ACTIVATION_TOKEN = os.getenv('SYNC_ACTIVATION_TOKEN', '')
SYNC_UPDATE_MANIFEST_URL = os.getenv('SYNC_UPDATE_MANIFEST_URL', '')
SYNC_INTERVAL_SECONDS = int(os.getenv('SYNC_INTERVAL_SECONDS', '30'))
SYNC_BATCH_SIZE = int(os.getenv('SYNC_BATCH_SIZE', '25'))
SYNC_REQUEST_TIMEOUT_SECONDS = int(os.getenv('SYNC_REQUEST_TIMEOUT_SECONDS', '20'))
SYNC_MAX_RETRY_ATTEMPTS = int(os.getenv('SYNC_MAX_RETRY_ATTEMPTS', '10'))
SYNC_MAX_PAYLOAD_BYTES = int(os.getenv('SYNC_MAX_PAYLOAD_BYTES', str(9 * 1024 * 1024)))
SYNC_BOOTSTRAP_VERSION = int(os.getenv('SYNC_BOOTSTRAP_VERSION', '3'))
# A 5 MB clinical document grows to about 6.7 MB when safely embedded in JSON.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', str(12 * 1024 * 1024)))



if os.getenv("DEBUG") == "True":  # Local/PostgreSQL
    DATABASES = {
        # "default": dj_database_url.config(default=os.getenv("DATABASE_URL"))
         "default": dj_database_url.config(conn_max_age=600)
    }
else:  # PythonAnywhere/MySQL
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE'),
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }
    
    


LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/select-clinic/'
LOGOUT_REDIRECT_URL = '/login/'

# AUTH_USER_MODEL = 'DurielMedicApp.CustomUser'
AUTH_USER_MODEL = 'core.CustomUser'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_ROOT = BASE_DIR / 'media'


# Add these at the bottom
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"




LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)  # ✅ auto-create logs folder if missing

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'django.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}



# Security settings
SECURE_SSL_REDIRECT = not (DEBUG or RUNNING_DEV_SERVER)
SESSION_COOKIE_SECURE = not (DEBUG or RUNNING_DEV_SERVER)
CSRF_COOKIE_SECURE = not (DEBUG or RUNNING_DEV_SERVER)
CSRF_COOKIE_HTTPONLY = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Additional modern security settings
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Session expires after 15 minutes of inactivity
SESSION_COOKIE_AGE = 900  # seconds (900 = 15 minutes)

# Reset the timer on each request (so active users aren’t logged out)
SESSION_SAVE_EVERY_REQUEST = True

# AUTO_LOGOUT_DELAY = 900  # seconds = 15 mins

CSRF_TRUSTED_ORIGINS = [
    'https://durielmedic.pythonanywhere.com',
    'https://www.durielmedic.pythonanywhere.com',
    'https://durielmedic.com.ng',
    'https://www.durielmedic.com.ng',
    *[origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()],
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings (for password reset and notifications)

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.go54mail.com"
EMAIL_PORT = 587
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = "info@durielmedic.com.ng"
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
DEFAULT_FROM_EMAIL = 'DurielMedic+ EMR <info@durielmedic.com.ng>'



# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'suavedef@gmail.com'
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
# EMAIL_USE_TLS = True 
# DEFAULT_FROM_EMAIL = 'DurielMedic+ EMR <suavedef@gmail.com>'

# AI Assist
AI_API_KEY = os.getenv("OPENROUTER_API_KEY")


# Paystack settings for payments
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')

# Stripe settings for payments
# STRIPE_PUBLIC_KEY = 'your_stripe_public_key'
# STRIPE_SECRET_KEY = 'your_stripe_secret_key'
# STRIPE_WEBHOOK_SECRET = 'your_stripe_webhook_secret'
