# Generated by Django 5.2.4 on 2025-08-12 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.clinic'),
            preserve_default=False,
        ),
    ]
