# Generated by Django 5.2.4 on 2025-08-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
