# Generated by Django 5.2.4 on 2026-08-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='appointment_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('appointment', 'eyeappointment', 'dentalappointment')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='labtestorder',
            name='appointment_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('appointment', 'eyeappointment', 'dentalappointment')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
