# Generated by Django 5.2.4 on 2026-08-11 16:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0009_vitals_bmi_vitals_height_vitals_oxygen_saturation_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_alter_billing_appointment_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('encounter_type', models.CharField(choices=[('GENERAL_CONSULTATION', 'General Consultation'), ('EYE_CONSULTATION', 'Eye Consultation'), ('DENTAL_CONSULTATION', 'Dental Consultation'), ('EMERGENCY', 'Emergency'), ('ADMISSION', 'Admission'), ('FOLLOW_UP', 'Follow-Up'), ('PROCEDURE', 'Procedure')], max_length=25)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DISCHARGED', 'Discharged'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=15)),
                ('appointment_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='DurielMedicApp.admission')),
                ('appointment_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_encounters', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='core.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='billing',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='core.patientencounter'),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='core.patientencounter'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='core.patientencounter'),
        ),
        migrations.AddIndex(
            model_name='patientencounter',
            index=models.Index(fields=['clinic', 'patient', '-started_at'], name='core_enc_clinic_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='patientencounter',
            index=models.Index(fields=['clinic', 'status'], name='core_enc_clinic_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientencounter',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment_content_type__isnull', False), ('appointment_object_id__isnull', False)), fields=('appointment_content_type', 'appointment_object_id'), name='core_unique_appointment_encounter'),
        ),
        migrations.AddConstraint(
            model_name='patientencounter',
            constraint=models.UniqueConstraint(condition=models.Q(('admission__isnull', False)), fields=('admission',), name='core_unique_admission_encounter'),
        ),
    ]
