# Generated by Django 5.2.4 on 2025-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_actionlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
