# Generated by Django 5.2.4 on 2026-08-11 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_patientencounter_billing_encounter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('appointment_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('CONSULTATION', 'Consultation'), ('LAB', 'Lab'), ('PRESCRIPTION', 'Prescription'), ('PROCEDURE', 'Procedure'), ('TREATMENT', 'Treatment'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('source_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('BILLED', 'Billed'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('appointment', 'eyeappointment', 'dentalappointment')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_line_items_for_appointment', to='contenttypes.contenttype')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_billing_line_items', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='core.billing')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_line_items', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_line_items', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_line_items', to='core.patientencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_line_items', to='core.patient')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_line_items', to='core.servicepricelist')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_line_items_for_source', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['clinic', 'status'], name='core_bi_clinic_status_idx'), models.Index(fields=['patient', 'status'], name='core_bi_patient_status_idx'), models.Index(fields=['appointment_content_type', 'appointment_object_id'], name='core_billitem_appt_idx'), models.Index(fields=['source_content_type', 'source_object_id'], name='core_billitem_source_idx')],
            },
        ),
    ]
