# Generated by Django 5.2.4 on 2026-08-11 18:15

import django.contrib.auth.validators
from django.db import migrations, models


def normalize_user_emails(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    seen = {}
    for user in CustomUser.objects.order_by('id'):
        email = (user.email or '').strip().lower()
        if not email:
            user.email = f"user{user.id}@legacy.local"
            user.save(update_fields=['email'])
            continue
        if email in seen:
            local, sep, domain = email.partition('@')
            if sep:
                user.email = f"{local}+user{user.id}@{domain}"
            else:
                user.email = f"user{user.id}@legacy.local"
            user.save(update_fields=['email'])
        else:
            if user.email != email:
                user.email = email
                user.save(update_fields=['email'])
            seen[email] = user.id


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0010_billinglineitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RunPython(normalize_user_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists in this clinic.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('primary_clinic__isnull', False)), fields=('primary_clinic', 'username'), name='core_unique_username_primary_clinic'),
        ),
    ]
