# Generated by Django 5.2.4 on 2026-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinglineitem',
            name='source_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('CONSULTATION', 'Consultation'), ('LAB', 'Lab'), ('PRESCRIPTION', 'Prescription'), ('PROCEDURE', 'Procedure'), ('ADMISSION', 'Admission'), ('PHYSIO_CONSULTATION', 'Physiotherapy Consultation'), ('PHYSIO_SESSION', 'Physiotherapy Session'), ('TREATMENT', 'Treatment'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20),
        ),
    ]
