# Generated by Django 5.2.4 on 2025-08-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='First', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Last', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered at Front Desk'), ('INSURANCE', 'HMO'), ('VITALS_TAKEN', 'Vitals Recorded'), ('IN_CONSULTATION', 'In Consultation'), ('ADMITTED', 'Admitted'), ('FOLLOW_UP', 'Scheduled for Follow-up'), ('FOLLOW_UP_COMPLETE', 'Follow-up Complete'), ('DISCHARGED', 'Discharged'), ('CONSULTATION_COMPLETE', 'Consultation Complete')], default='REGISTERED', max_length=25),
        ),
    ]
