# Generated by Django 5.2.4 on 2026-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_billinglineitem_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('OPTOMETRIST', 'Optometrist'), ('OPTICIAN', 'Optician'), ('DENTIST', 'Dentist'), ('PHYSIOTHERAPIST', 'Physiotherapist'), ('RECEPTIONIST', 'Receptionist'), ('LAB_TECHNICIAN', 'Lab Technician')], default='DOCTOR', max_length=15),
        ),
    ]
