# Generated by Django 5.2.4 on 2025-08-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_servicepricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='bills', to='core.servicepricelist'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
