# Generated by Django 5.2.4 on 2025-08-19 17:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_billing_services_alter_billing_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationcategory',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_categories', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='medicationcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 19, 17, 34, 17, 883414, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
