# Generated by Django 5.2.4 on 2025-08-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0017_medicationcategory_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='appointment',
        ),
        migrations.AddField(
            model_name='billing',
            name='appointment_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('appointment', 'eyeappointment')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='billing',
            name='appointment_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
