# Generated by Django 5.2.4 on 2025-09-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_billing_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='last_reminder_sent',
            field=models.CharField(choices=[('NONE', 'None'), ('D14', '14 days'), ('D7', '7 days'), ('D0', 'Expiry day')], default='NONE', max_length=8),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10, null=True),
        ),
    ]
