# Generated by Django 5.2.4 on 2026-08-24 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0015_alter_vitals_appointment'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0018_clinic_patient_id_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_scope', models.CharField(default='general', max_length=30)),
                ('report_type', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('file', models.FileField(blank=True, upload_to='report_exports/')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['clinic', '-timestamp'], name='core_actionlog_clinic_time_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['user', '-timestamp'], name='core_actionlog_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['clinic', 'status', '-created_at'], name='core_bill_clin_stat_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['clinic', 'service_date'], name='core_bill_clinic_service_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['patient', 'status'], name='core_bill_patient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['clinic', '-updated_at'], name='core_bill_clinic_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_subscription_active', 'subscription_type'], name='core_clinic_subact_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['subscription_start_date'], name='core_clinic_sub_start_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['subscription_end_date'], name='core_clinic_sub_end_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['created_at'], name='core_clinic_created_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'created_at'], name='core_pat_clinic_created_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'updated_at'], name='core_pat_clinic_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'last_name', 'first_name'], name='core_patient_clinic_name_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'status'], name='core_patient_clinic_status_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinic', 'date_prescribed'], name='core_rx_clinic_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinic', 'is_active'], name='core_rx_clinic_active_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'date_prescribed'], name='core_rx_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinic', 'stock_deducted'], name='core_rx_clinic_stock_idx'),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_export_jobs', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_export_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reportexportjob',
            index=models.Index(fields=['clinic', 'status', '-created_at'], name='core_rjob_clin_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportjob',
            index=models.Index(fields=['requested_by', '-created_at'], name='core_rjob_user_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportjob',
            index=models.Index(fields=['report_scope', 'report_type'], name='core_reportjob_type_idx'),
        ),
    ]
