# Generated by Django 5.2.4 on 2026-01-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_clinic_is_subscription_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="subscription_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRIAL", "Trial"),
                    ("MONTHLY", "Monthly"),
                    ("YEARLY", "Yearly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
