# Generated by Django 5.2.4 on 2026-01-29 07:52

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0020_alter_clinic_subscription_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="billing",
            name="discount_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="discount_applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_discounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="discount_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="billing",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("NONE", "No Discount"),
                    ("PERCENTAGE", "Percentage"),
                    ("FIXED", "Fixed Amount"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage (0-100) or fixed amount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="final_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("OPTOMETRIST", "Optometrist"),
                    ("PHYSIOTHERAPIST", "Physiotherapist"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("LAB_TECHNICIAN", "Lab Technician"),
                ],
                default="DOCTOR",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="LabTestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood Tests"),
                            ("URINE", "Urine Tests"),
                            ("IMAGING", "Imaging/Radiology"),
                            ("MICROBIOLOGY", "Microbiology"),
                            ("BIOCHEMISTRY", "Biochemistry"),
                            ("PATHOLOGY", "Pathology"),
                            ("CARDIOLOGY", "Cardiology Tests"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_categories",
                        to="core.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lab Test Categories",
                "ordering": ["name"],
                "unique_together": {("clinic", "name")},
            },
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Unique test code for this clinic",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("STOOL", "Stool"),
                            ("SALIVA", "Saliva"),
                            ("TISSUE", "Tissue"),
                            ("SWAB", "Swab"),
                            ("NONE", "No Sample Required"),
                            ("OTHER", "Other"),
                        ],
                        default="BLOOD",
                        max_length=20,
                    ),
                ),
                (
                    "turnaround_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '24 hours', '3-5 days'",
                        max_length=100,
                    ),
                ),
                (
                    "preparation_instructions",
                    models.TextField(
                        blank=True, help_text="Patient preparation instructions"
                    ),
                ),
                (
                    "reference_range",
                    models.TextField(
                        blank=True, help_text="Normal reference range for this test"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_tests",
                        to="core.clinic",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests",
                        to="core.labtestcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
                "unique_together": {("clinic", "code")},
            },
        ),
        migrations.CreateModel(
            name="LabTestOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ORDERED", "Ordered"),
                            ("IN_QUEUE", "In Queue"),
                            ("SAMPLE_COLLECTED", "Sample Collected"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("REVIEWED", "Reviewed by Doctor"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ORDERED",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=10,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True, help_text="Clinical notes from ordering doctor"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, help_text="Suspected diagnosis"),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("sample_collected_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment_content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "model__in": ("appointment", "eyeappointment")
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "billing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders",
                        to="core.billing",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_orders",
                        to="core.clinic",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordered_tests",
                    models.ManyToManyField(related_name="orders", to="core.labtest"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_orders",
                        to="core.patient",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample_collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_samples_collected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="LabTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_value",
                    models.TextField(
                        blank=True, help_text="Test result value/findings"
                    ),
                ),
                (
                    "reference_range",
                    models.CharField(
                        blank=True, help_text="Normal reference range", max_length=200
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measurement", max_length=50
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(
                        default=False,
                        help_text="Flag if result is outside normal range",
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload result document (PDF, JPG, PNG - max 5MB)",
                        null=True,
                        upload_to=core.models.lab_result_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            ),
                            core.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "result_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the result"
                    ),
                ),
                (
                    "technician_comments",
                    models.TextField(blank=True, help_text="Lab technician comments"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lab_test_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.labtestorder",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_results_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.labtest",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_results_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["test__name"],
            },
        ),
        migrations.AddIndex(
            model_name="labtestorder",
            index=models.Index(fields=["status"], name="core_labtes_status_9c3c00_idx"),
        ),
        migrations.AddIndex(
            model_name="labtestorder",
            index=models.Index(
                fields=["priority"], name="core_labtes_priorit_d29caa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labtestorder",
            index=models.Index(
                fields=["-ordered_at"], name="core_labtes_ordered_86f64b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labtestresult",
            unique_together={("lab_test_order", "test")},
        ),
    ]
