# Generated by Django 5.2.4 on 2026-02-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_lab_models_and_billing_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("PHARMACIST", "Pharmacist"),
                    ("OPTOMETRIST", "Optometrist"),
                    ("PHYSIOTHERAPIST", "Physiotherapist"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("LAB_TECHNICIAN", "Lab Technician"),
                ],
                default="DOCTOR",
                max_length=15,
            ),
        ),
    ]
