# Generated by Django 5.2.4 on 2025-08-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_acuity', models.CharField(max_length=20)),
                ('intraocular_pressure', models.FloatField()),
            ],
        ),
    ]
