# Generated by Django 5.2.4 on 2026-08-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('SELF', 'Self Paid'), ('INSURANCE', 'Insurance')], default='SELF', max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EyeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_acuity_right', models.CharField(blank=True, max_length=20, null=True)),
                ('visual_acuity_left', models.CharField(blank=True, max_length=20, null=True)),
                ('intraocular_pressure_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intraocular_pressure_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('slit_lamp_findings', models.TextField(blank=True, null=True)),
                ('fundus_exam_findings', models.TextField(blank=True, null=True)),
                ('refraction_right', models.CharField(blank=True, max_length=50, null=True)),
                ('refraction_left', models.CharField(blank=True, max_length=50, null=True)),
                ('sphere_right', models.CharField(default='Not recorded', max_length=50)),
                ('cylinder_right', models.CharField(default='Not recorded', max_length=50)),
                ('axis_right', models.CharField(default='Not recorded', max_length=50)),
                ('add_right', models.CharField(default='Not recorded', max_length=50)),
                ('pupil_size_right', models.CharField(default='Not recorded mm', max_length=50)),
                ('sphere_left', models.CharField(default='Not recorded', max_length=50)),
                ('cylinder_left', models.CharField(default='Not recorded', max_length=50)),
                ('axis_left', models.CharField(default='Not recorded', max_length=50)),
                ('add_left', models.CharField(default='Not recorded', max_length=50)),
                ('pupil_size_left', models.CharField(default='Not recorded mm', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EyeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EyeMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('DIAGNOSIS', 'Diagnosis'), ('TREATMENT', 'Treatment Plan'), ('PROGRESS', 'Progress Note'), ('IMAGING', 'Imaging Result'), ('PRESCRIPTION', 'Prescription'), ('PROCEDURE', 'Procedure'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
