# Generated by Django 5.2.4 on 2026-08-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DurielEyeApp', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeappointment',
            name='clinic',
            field=models.ForeignKey(limit_choices_to={'clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_appointments', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='eyeappointment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eyeappointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'clinic__clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_appointments', to='core.patient'),
        ),
        migrations.AddField(
            model_name='eyeappointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DurielEyeApp.eyeappointment'),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_exams', to='core.patient'),
        ),
        migrations.AddField(
            model_name='eyefollowup',
            name='clinic',
            field=models.ForeignKey(limit_choices_to={'clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_follow_ups', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='eyefollowup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eyefollowup',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'clinic__clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_follow_ups', to='core.patient'),
        ),
        migrations.AddField(
            model_name='eyemedicalrecord',
            name='clinic',
            field=models.ForeignKey(limit_choices_to={'clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_medical_records', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='eyemedicalrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eyemedicalrecord',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'clinic__clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_medical_records', to='core.patient'),
        ),
    ]
