# Generated by Django 5.2.4 on 2025-08-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("DurielEyeApp", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eyeexam",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"clinic__clinic_type": "EYE"},
                on_delete=django.db.models.deletion.CASCADE,
                to="core.patient",
            ),
        ),
    ]
