# Generated by Django 5.2.4 on 2025-08-14 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0002_initial'),
        ('core', '0009_alter_actionlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyeexam',
            name='intraocular_pressure',
        ),
        migrations.RemoveField(
            model_name='eyeexam',
            name='visual_acuity',
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='fundus_exam_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='intraocular_pressure_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='intraocular_pressure_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='refraction_left',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='refraction_right',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='slit_lamp_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='visual_acuity_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='visual_acuity_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyeexam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_exams', to='core.patient'),
        ),
        migrations.CreateModel(
            name='EyeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(limit_choices_to={'clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_appointments', to='core.clinic')),
                ('patient', models.ForeignKey(limit_choices_to={'clinic__clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_appointments', to='core.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DurielEyeApp.eyeappointment'),
        ),
        migrations.CreateModel(
            name='EyeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(limit_choices_to={'clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_follow_ups', to='core.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'clinic__clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_follow_ups', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EyeMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('DIAGNOSIS', 'Diagnosis'), ('TREATMENT', 'Treatment Plan'), ('PROGRESS', 'Progress Note'), ('IMAGING', 'Imaging Result'), ('PRESCRIPTION', 'Prescription'), ('PROCEDURE', 'Procedure'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(limit_choices_to={'clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_medical_records', to='core.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'clinic__clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eye_medical_records', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EyeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('clinic', models.ForeignKey(blank=True, limit_choices_to={'clinic_type': 'EYE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eye_notifications', to='core.clinic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eye_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EyeNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DurielEyeApp.eyenotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
