# Generated by Django 5.2.4 on 2026-08-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0003_eye_sync_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexam',
            name='anterior_segment_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='eye_allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='final_prescription_left',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='final_prescription_right',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='follow_up_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='imaging_results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='lens_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='near_vision_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='near_vision_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='objective_refraction_left',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='objective_refraction_right',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='ocular_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='ocular_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='optic_disc_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='pinhole_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='pinhole_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='posterior_segment_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='procedure_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='pupillary_distance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='retina_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='spectacle_or_contact_lens_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='systemic_risk_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='visual_acuity_left_corrected',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='visual_acuity_right_corrected',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eyefollowup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
