# Generated by Django 5.2.4 on 2025-08-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0003_remove_eyeexam_intraocular_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexam',
            name='add_left',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='add_right',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='axis_left',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='axis_right',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='cylinder_left',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='cylinder_right',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='pupil_size_left',
            field=models.CharField(default='Not recorded mm', max_length=50),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='pupil_size_right',
            field=models.CharField(default='Not recorded mm', max_length=50),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='sphere_left',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='sphere_right',
            field=models.CharField(default='Not recorded', max_length=50),
        ),
    ]
