# Generated by Django 5.2.4 on 2026-08-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0004_eyeexam_anterior_segment_findings_and_more'),
        ('core', '0009_patientencounter_billing_encounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexam',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_exams', to='core.patientencounter'),
        ),
    ]
