# Generated by Django 5.2.4 on 2025-08-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0004_eyeexam_add_left_eyeexam_add_right_eyeexam_axis_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyenotificationread',
            name='notification',
        ),
        migrations.AlterUniqueTogether(
            name='eyenotificationread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eyenotificationread',
            name='user',
        ),
        migrations.DeleteModel(
            name='EyeNotification',
        ),
        migrations.DeleteModel(
            name='EyeNotificationRead',
        ),
    ]
