# Generated by Django 5.2.4 on 2026-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0005_eyeexam_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexam',
            name='base_direction_left',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='base_direction_right',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='colour_vision',
            field=models.CharField(blank=True, help_text='Colour vision (e.g. Ishihara 14/14)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='confrontation_visual_fields',
            field=models.CharField(blank=True, help_text='Confrontation visual fields', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='cover_test',
            field=models.CharField(blank=True, help_text='Cover test / phorias / tropias', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='cup_disc_ratio_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='cup_disc_ratio_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='extraocular_motility',
            field=models.CharField(blank=True, help_text='Extraocular movements / motility', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='iop_method',
            field=models.CharField(blank=True, help_text='Tonometry method (Goldmann / NCT / Tono-pen)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='iop_time',
            field=models.CharField(blank=True, help_text='Time IOP measured', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='keratometry_left',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='keratometry_right',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='pachymetry_left',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='pachymetry_right',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='prism_left',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='prism_right',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='pupils_perrla',
            field=models.CharField(blank=True, help_text='PERRLA / pupil reactions', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='rapd_note',
            field=models.CharField(blank=True, help_text='Relative afferent pupillary defect (RAPD)', max_length=100, null=True),
        ),
    ]
