# Generated by Django 5.2.4 on 2025-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0006_eyeappointment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeappointment',
            name='payment_type',
            field=models.CharField(choices=[('SELF', 'Self Paid'), ('INSURANCE', 'Insurance')], default='SELF', max_length=10),
        ),
    ]
