# Generated by Django 5.2.4 on 2026-08-19 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0006_eyeexam_base_direction_left_and_more'),
        ('core', '0013_alter_billinglineitem_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_type', models.CharField(choices=[('FRAME', 'Frame'), ('SPECTACLE_LENS', 'Spectacle Lens'), ('CONTACT_LENS', 'Contact Lens'), ('ACCESSORY', 'Accessory')], default='FRAME', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120, null=True)),
                ('model_code', models.CharField(blank=True, max_length=100, null=True)),
                ('colour', models.CharField(blank=True, max_length=60, null=True)),
                ('size', models.CharField(blank=True, max_length=60, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('sphere', models.CharField(blank=True, max_length=30, null=True)),
                ('cylinder', models.CharField(blank=True, max_length=30, null=True)),
                ('axis', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock_level', models.PositiveIntegerField(default=5)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=15)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(limit_choices_to={'clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='optical_products', to='core.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpticalDispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optical_dispenses', to='DurielEyeApp.eyeappointment')),
                ('clinic', models.ForeignKey(limit_choices_to={'clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='optical_dispenses', to='core.clinic')),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optical_dispenses', to='core.patientencounter')),
                ('eye_exam', models.ForeignKey(blank=True, help_text='Source spectacle/contact-lens prescription, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optical_dispenses', to='DurielEyeApp.eyeexam')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optical_dispenses', to='core.patient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='DurielEyeApp.opticalproduct')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='OpticalStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Stock Adjustment'), ('EXPIRED', 'Expired Stock'), ('DAMAGED', 'Damaged Stock')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='DurielEyeApp.opticalproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
