# Generated by Django 5.2.4 on 2026-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0007_opticalproduct_opticaldispense_opticalstockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexam',
            name='frame_prescribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='frame_prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='lens_prescribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='lens_prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
