# Generated by Django 5.2.4 on 2026-08-19 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0008_eyeexam_frame_prescribed_eyeexam_frame_prescription_and_more'),
        ('core', '0014_alter_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticalPrescriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('frame_prescription', models.TextField(blank=True, null=True)),
                ('lens_prescription', models.TextField(blank=True, null=True)),
                ('optician_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('PROCESSED', 'Processed'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_optical_prescription_requests', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optical_prescription_requests', to='DurielEyeApp.eyeappointment')),
                ('clinic', models.ForeignKey(limit_choices_to={'clinic_type': 'EYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='optical_prescription_requests', to='core.clinic')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_optical_prescription_requests', to=settings.AUTH_USER_MODEL)),
                ('eye_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optical_prescription_request', to='DurielEyeApp.eyeexam')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optical_prescription_requests', to='core.patient')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_optical_prescription_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_optical_prescription_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
