# Generated by Django 5.2.4 on 2026-08-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0009_opticalprescriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexam',
            name='frame_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'FRAME'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_exam_prescriptions', to='DurielEyeApp.opticalproduct'),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='lens_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type__in': ['SPECTACLE_LENS', 'CONTACT_LENS']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lens_exam_prescriptions', to='DurielEyeApp.opticalproduct'),
        ),
    ]
