# Generated by Django 5.2.4 on 2026-08-19 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0010_eyeexam_frame_product_eyeexam_lens_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticalprescriptionrequest',
            name='frame_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_prescription_requests', to='DurielEyeApp.opticalproduct'),
        ),
        migrations.AddField(
            model_name='opticalprescriptionrequest',
            name='lens_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lens_prescription_requests', to='DurielEyeApp.opticalproduct'),
        ),
    ]
