# Generated by Django 5.2.4 on 2026-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielEyeApp', '0011_opticalprescriptionrequest_frame_product_and_more'),
        ('core', '0020_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexam',
            name='optical_services',
            field=models.ManyToManyField(blank=True, help_text='Billable optical services selected from the clinic service list.', related_name='eye_exam_optical_requests', to='core.servicepricelist'),
        ),
        migrations.AddField(
            model_name='eyeexam',
            name='optician_order',
            field=models.TextField(blank=True, help_text='Manual job order/instruction sent to the optician.', null=True),
        ),
        migrations.AddField(
            model_name='opticalprescriptionrequest',
            name='optician_order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
