import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('DurielDentalApp', '0002_initial'),
        ('core', '0004_prescription_sync_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(name='DentalExam'),
        migrations.CreateModel(
            name='DentalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visit_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('CHECKUP', 'Routine Checkup'), ('CLEANING', 'Scaling/Cleaning'), ('RESTORATION', 'Restoration/Filling'), ('EXTRACTION', 'Extraction'), ('ROOT_CANAL', 'Root Canal'), ('ORTHODONTICS', 'Orthodontics'), ('SURGERY', 'Oral Surgery'), ('EMERGENCY', 'Emergency')], default='CONSULTATION', max_length=20)),
                ('payment_type', models.CharField(choices=[('SELF', 'Self Paid'), ('INSURANCE', 'Insurance')], default='SELF', max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('chief_complaint', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked In'), ('IN_CHAIR', 'In Chair'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(limit_choices_to={'clinic_type': 'DENTAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='dental_appointments', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dental_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'clinic__clinic_type': 'DENTAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='dental_appointments', to='core.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['date', 'start_time'], 'indexes': [models.Index(fields=['clinic', 'date', 'status'], name='DurielDenta_clinic__38b4d8_idx'), models.Index(fields=['provider', 'date'], name='DurielDenta_provide_22c781_idx')]},
        ),
        migrations.CreateModel(
            name='DentalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('medical_alerts', models.TextField(blank=True)),
                ('extraoral_exam', models.TextField(blank=True)),
                ('intraoral_exam', models.TextField(blank=True)),
                ('periodontal_findings', models.TextField(blank=True)),
                ('occlusion', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('CLASS_I', 'Class I'), ('CLASS_II', 'Class II'), ('CLASS_III', 'Class III'), ('OPEN_BITE', 'Open Bite'), ('CROSS_BITE', 'Cross Bite')], max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_recommendation', models.TextField(blank=True)),
                ('tooth_chart', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='DurielDentalApp.dentalappointment')),
                ('clinic', models.ForeignKey(limit_choices_to={'clinic_type': 'DENTAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='dental_exams', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'clinic__clinic_type': 'DENTAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='dental_exams', to='core.patient')),
            ],
            options={'ordering': ['-created_at'], 'indexes': [models.Index(fields=['patient', '-created_at'], name='DurielDenta_patient_960a02_idx'), models.Index(fields=['clinic', '-created_at'], name='DurielDenta_clinic__94af23_idx')]},
        ),
        migrations.CreateModel(
            name='DentalMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('record_type', models.CharField(choices=[('DIAGNOSIS', 'Diagnosis'), ('TREATMENT_NOTE', 'Treatment Note'), ('IMAGING', 'Imaging/X-ray'), ('PRESCRIPTION', 'Prescription'), ('CONSENT', 'Consent'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_medical_records', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_medical_records', to='core.patient')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='DentalTreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('diagnosis', models.TextField(blank=True)),
                ('proposed_treatment', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', max_length=12)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='PROPOSED', max_length=12)),
                ('consent_obtained', models.BooleanField(default=False)),
                ('consent_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_treatment_plans', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='DurielDentalApp.dentalexam')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_treatment_plans', to='core.patient')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='DentalFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_follow_ups', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_follow_ups', to='core.patient')),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='DurielDentalApp.dentaltreatmentplan')),
            ],
            options={'ordering': ['scheduled_date', 'scheduled_time']},
        ),
        migrations.CreateModel(
            name='DentalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tooth_numbers', models.CharField(blank=True, help_text='FDI/Universal notation, e.g. 11, 12, 36', max_length=100)),
                ('procedure_name', models.CharField(max_length=200)),
                ('materials_used', models.TextField(blank=True)),
                ('anesthesia', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DONE', max_length=10)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='DurielDentalApp.dentalappointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_procedures', to='core.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_procedures', to='core.patient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='DurielDentalApp.dentaltreatmentplan')),
            ],
            options={'ordering': ['-performed_at'], 'indexes': [models.Index(fields=['patient', '-performed_at'], name='DurielDenta_patient_c19f21_idx'), models.Index(fields=['clinic', '-performed_at'], name='DurielDenta_clinic__9d1540_idx')]},
        ),
    ]
