# Generated by Django 5.2.4 on 2026-08-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DurielDentalApp', '0003_standard_dental_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalprocedure',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='dentaltreatmentplan',
            name='estimated_cost',
        ),
    ]
