# Generated by Django 5.2.4 on 2026-08-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielDentalApp', '0004_remove_dentalprocedure_cost_and_more'),
        ('core', '0009_patientencounter_billing_encounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalexam',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_exams', to='core.patientencounter'),
        ),
        migrations.AddField(
            model_name='dentalmedicalrecord',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_records', to='core.patientencounter'),
        ),
        migrations.AddField(
            model_name='dentalprocedure',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_procedures', to='core.patientencounter'),
        ),
        migrations.AddField(
            model_name='dentaltreatmentplan',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_treatment_plans', to='core.patientencounter'),
        ),
    ]
