# Generated by Codex on 2026-09-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DurielDentalApp', '0005_dentalexam_encounter_dentalmedicalrecord_encounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalfollowup',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_follow_ups', to=settings.AUTH_USER_MODEL),
        ),
    ]
