# Generated by Django 5.2.4 on 2026-08-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('date_admitted', models.DateTimeField(auto_now_add=True)),
                ('discharged', models.BooleanField(default=False)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_admitted'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('SELF', 'Self Paid'), ('INSURANCE', 'Insurance')], default='SELF', max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='Chief Complaint')),
                ('history_of_present_illness', models.TextField(blank=True, verbose_name='History of Present Illness')),
                ('past_medical_history', models.TextField(blank=True, verbose_name='Past Medical History')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnosis')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='Treatment Plan')),
                ('lab_results', models.TextField(blank=True, verbose_name='Lab Results')),
                ('imaging_results', models.TextField(blank=True, verbose_name='Imaging Results')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('procedures', models.TextField(blank=True, verbose_name='Procedures')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysiotherapyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='Chief Complaint')),
                ('history_of_present_illness', models.TextField(blank=True, verbose_name='History of Present Illness')),
                ('past_medical_history', models.TextField(blank=True, verbose_name='Past Medical History')),
                ('physical_examination', models.TextField(blank=True, verbose_name='Physical Examination')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnosis')),
                ('treatment_goals', models.TextField(blank=True, verbose_name='Treatment Goals')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='Treatment Plan')),
                ('exercises_prescribed', models.TextField(blank=True, verbose_name='Exercises Prescribed')),
                ('modalities_used', models.TextField(blank=True, verbose_name='Modalities Used')),
                ('progress_notes', models.TextField(blank=True, verbose_name='Progress Notes')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=10)),
                ('pulse', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('weight', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('CONSULT', 'Consultation'), ('FOLLOWUP', 'Follow-Up')], max_length=20)),
            ],
        ),
    ]
