# Generated by Django 5.2.4 on 2025-07-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DurielMedicApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="name",
            field=models.CharField(
                choices=[("DURIEL_CLINIC", "duriel clinic")], max_length=100
            ),
        ),
    ]
