# Generated by Django 5.2.4 on 2025-07-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DurielMedicApp", "0002_alter_clinic_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
