# Generated by Django 5.2.4 on 2025-08-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0003_notification_clinic_alter_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
