# Generated by Django 5.2.4 on 2025-08-05 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DurielMedicApp", "0003_alter_clinic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "Registered at Front Desk"),
                    ("VITALS_TAKEN", "Vitals Recorded"),
                    ("IN_CONSULTATION", "In Consultation"),
                    ("ADMITTED", "Admitted"),
                    ("FOLLOW_UP", "Scheduled for Follow-up"),
                    ("DISCHARGED", "Discharged"),
                    ("CONSULTATION_COMPLETE", "Consultation Complete"),
                ],
                default="REGISTERED",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("date_admitted", models.DateTimeField(auto_now_add=True)),
                ("ward", models.CharField(max_length=50)),
                ("discharged", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DurielMedicApp.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_pressure", models.CharField(max_length=10)),
                ("pulse", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("weight", models.FloatField()),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONSULT", "Consultation"),
                            ("FOLLOWUP", "Follow-Up"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DurielMedicApp.appointment",
                    ),
                ),
            ],
        ),
    ]
