# Generated by Django 5.2.4 on 2025-08-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0004_delete_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationread',
            name='notification',
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationread',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationRead',
        ),
    ]
