# Generated by Django 5.2.4 on 2025-08-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DurielMedicApp", "0005_followup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "Registered at Front Desk"),
                    ("VITALS_TAKEN", "Vitals Recorded"),
                    ("IN_CONSULTATION", "In Consultation"),
                    ("ADMITTED", "Admitted"),
                    ("FOLLOW_UP", "Scheduled for Follow-up"),
                    ("FOLLOW_UP_COMPLETE", "Follow-up Complete"),
                    ("DISCHARGED", "Discharged"),
                    ("CONSULTATION_COMPLETE", "Consultation Complete"),
                ],
                default="REGISTERED",
                max_length=25,
            ),
        ),
    ]
