# Generated by Django 5.2.4 on 2025-08-06 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DurielMedicApp", "0006_alter_patient_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view_all_patients", "Can view all patients"),
                    ("can_edit_patient_records", "Can edit patient records"),
                    ("can_delete_patient_records", "Can delete patient records"),
                    ("can_create_prescriptions", "Can create prescriptions"),
                    ("can_view_reports", "Can view reports"),
                    ("can_manage_staff", "Can manage staff"),
                    ("can_create_bills", "Can create bills"),
                    ("can_edit_bills", "Can edit bills"),
                    ("can_delete_bills", "Can delete bills"),
                    ("can_record_payments", "Can record payments"),
                    ("can_view_financial_reports", "Can view financial reports"),
                ]
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CHEQUE", "Cheque"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="DurielMedicApp.billing",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
    ]
