# Generated by Django 5.2.4 on 2026-01-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DurielMedicApp", "0006_appointment_payment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="description",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="record_type",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="title",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="additional_notes",
            field=models.TextField(blank=True, verbose_name="Additional Notes"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="allergies",
            field=models.TextField(blank=True, verbose_name="Allergies"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="chief_complaint",
            field=models.TextField(blank=True, verbose_name="Chief Complaint"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="diagnosis",
            field=models.TextField(blank=True, verbose_name="Diagnosis"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="history_of_present_illness",
            field=models.TextField(
                blank=True, verbose_name="History of Present Illness"
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="imaging_results",
            field=models.TextField(blank=True, verbose_name="Imaging Results"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="lab_results",
            field=models.TextField(blank=True, verbose_name="Lab Results"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="past_medical_history",
            field=models.TextField(blank=True, verbose_name="Past Medical History"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="procedures",
            field=models.TextField(blank=True, verbose_name="Procedures"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="treatment_plan",
            field=models.TextField(blank=True, verbose_name="Treatment Plan"),
        ),
    ]
