# Generated by Django 5.2.4 on 2026-08-11 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0007_medication_administration_billing'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='appointment_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('appointment', 'eyeappointment', 'dentalappointment')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='appointment_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DurielMedicApp.appointment'),
        ),
    ]
