# Generated by Django 5.2.4 on 2026-01-28 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DurielMedicApp", "0007_remove_medicalrecord_description_and_more"),
        ("core", "0020_alter_clinic_subscription_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysiotherapyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, verbose_name="Chief Complaint"),
                ),
                (
                    "history_of_present_illness",
                    models.TextField(
                        blank=True, verbose_name="History of Present Illness"
                    ),
                ),
                (
                    "past_medical_history",
                    models.TextField(blank=True, verbose_name="Past Medical History"),
                ),
                (
                    "physical_examination",
                    models.TextField(blank=True, verbose_name="Physical Examination"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Diagnosis")),
                (
                    "treatment_goals",
                    models.TextField(blank=True, verbose_name="Treatment Goals"),
                ),
                (
                    "treatment_plan",
                    models.TextField(blank=True, verbose_name="Treatment Plan"),
                ),
                (
                    "exercises_prescribed",
                    models.TextField(blank=True, verbose_name="Exercises Prescribed"),
                ),
                (
                    "modalities_used",
                    models.TextField(blank=True, verbose_name="Modalities Used"),
                ),
                (
                    "progress_notes",
                    models.TextField(blank=True, verbose_name="Progress Notes"),
                ),
                (
                    "additional_notes",
                    models.TextField(blank=True, verbose_name="Additional Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physiotherapy_records",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
