# Generated by Django 5.2.4 on 2026-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0008_vitals_appointment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='oxygen_saturation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
