# Generated by Django 5.2.4 on 2026-08-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0009_vitals_bmi_vitals_height_vitals_oxygen_saturation_and_more'),
        ('core', '0009_patientencounter_billing_encounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_records', to='core.patientencounter'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_records', to='core.patientencounter'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals', to='core.patientencounter'),
        ),
    ]
