# Generated by Django 5.2.4 on 2026-02-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DurielMedicApp", "0009_admission_tracking_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="admission",
            new_name="DurielMedic_clinic__186e9a_idx",
            old_name="DurielMedic_clinic_i_8b0e0f_idx",
        ),
        migrations.RenameIndex(
            model_name="admission",
            new_name="DurielMedic_dischar_a7224e_idx",
            old_name="DurielMedic_discharg_f16b68_idx",
        ),
        migrations.RenameIndex(
            model_name="admission",
            new_name="DurielMedic_date_ad_64fa60_idx",
            old_name="DurielMedic_date_ad_6a70d9_idx",
        ),
    ]
