# Generated by Django 5.2.4 on 2026-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0011_physiotherapyreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapyrecord',
            name='session_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='physiotherapyrecord',
            name='session_dates',
            field=models.TextField(blank=True, help_text='One physiotherapy session date per line.'),
        ),
    ]
