# Generated by Django 5.2.4 on 2026-08-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0012_physiotherapyrecord_session_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapyrecord',
            name='session_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
