# Generated by Django 5.2.4 on 2026-08-19 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DurielMedicApp', '0014_nurseinstruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DurielMedicApp.appointment'),
        ),
    ]
