# Generated by Codex on 2026-09-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('DurielMedicApp', '0016_followup_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='appointment_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('appointment', 'eyeappointment', 'dentalappointment', 'followup', 'eyefollowup', 'dentalfollowup')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
